<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.apache.org/axis2" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.apache.org/axis2" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
  </wsdl:types>
  <wsdl:portType name="__MultitenantDispatcherServicePortType">
    <wsdl:operation name="dispatch">
      <wsdl:input message="tns:null" wsaw:Action="urn:dispatch">
    </wsdl:input>
      <wsdl:output message="tns:null" wsaw:Action="urn:dispatchResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="__MultitenantDispatcherServiceSoap11Binding" type="tns:__MultitenantDispatcherServicePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="dispatch">
      <soap:operation soapAction="urn:dispatch" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="__MultitenantDispatcherServiceSoap12Binding" type="tns:__MultitenantDispatcherServicePortType">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="dispatch">
      <soap12:operation soapAction="urn:dispatch" style="document"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="__MultitenantDispatcherServiceHttpBinding" type="tns:__MultitenantDispatcherServicePortType">
    <http:binding verb="POST"/>
    <wsdl:operation name="dispatch">
      <http:operation location="dispatch"/>
      <wsdl:input>
        <mime:content part="parameters" type="text/xml"/>
      </wsdl:input>
      <wsdl:output>
        <mime:content part="parameters" type="text/xml"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="__MultitenantDispatcherService">
    <wsdl:port name="__MultitenantDispatcherServiceHttpsSoap12Endpoint" binding="tns:__MultitenantDispatcherServiceSoap12Binding">
      <soap12:address location="https://cloud-test.wso2.com:9443/services/__MultitenantDispatcherService.__MultitenantDispatcherServiceHttpsSoap12Endpoint/"/>
    </wsdl:port>
    <wsdl:port name="__MultitenantDispatcherServiceHttpsEndpoint" binding="tns:__MultitenantDispatcherServiceHttpBinding">
      <http:address location="https://cloud-test.wso2.com:9443/services/__MultitenantDispatcherService.__MultitenantDispatcherServiceHttpsEndpoint/"/>
    </wsdl:port>
    <wsdl:port name="__MultitenantDispatcherServiceHttpsSoap11Endpoint" binding="tns:__MultitenantDispatcherServiceSoap11Binding">
      <soap:address location="https://cloud-test.wso2.com:9443/services/__MultitenantDispatcherService.__MultitenantDispatcherServiceHttpsSoap11Endpoint/"/>
    </wsdl:port>
    <wsdl:port name="__MultitenantDispatcherServiceHttpSoap11Endpoint" binding="tns:__MultitenantDispatcherServiceSoap11Binding">
      <soap:address location="http://cloud-test.wso2.com:9763/services/__MultitenantDispatcherService.__MultitenantDispatcherServiceHttpSoap11Endpoint/"/>
    </wsdl:port>
    <wsdl:port name="__MultitenantDispatcherServiceHttpEndpoint" binding="tns:__MultitenantDispatcherServiceHttpBinding">
      <http:address location="http://cloud-test.wso2.com:9763/services/__MultitenantDispatcherService.__MultitenantDispatcherServiceHttpEndpoint/"/>
    </wsdl:port>
    <wsdl:port name="__MultitenantDispatcherServiceHttpSoap12Endpoint" binding="tns:__MultitenantDispatcherServiceSoap12Binding">
      <soap12:address location="http://cloud-test.wso2.com:9763/services/__MultitenantDispatcherService.__MultitenantDispatcherServiceHttpSoap12Endpoint/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
