<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.apache.org/axis2" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://ws.apache.org/axis2" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
<wsdl:documentation>sts-ic-symm</wsdl:documentation>
  <wsdl:types>
  </wsdl:types>
  <wsdl:message name="IssueTokenResponse">
  </wsdl:message>
  <wsdl:message name="IssueTokenRequest">
  </wsdl:message>
  <wsdl:portType name="sts-ic-symmPortType">
    <wsdl:operation name="IssueToken">
      <wsdl:input message="tns:IssueTokenRequest" wsaw:Action="http://schemas.xmlsoap.org/ws/2005/02/trust/RST/SCT">
    </wsdl:input>
      <wsdl:output message="tns:IssueTokenResponse" wsaw:Action="urn:IssueTokenResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="sts-ic-symmSoap11Binding" type="tns:sts-ic-symmPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="IssueToken">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="sts-ic-symmHttpBinding" type="tns:sts-ic-symmPortType">
    <http:binding verb="POST"/>
    <wsdl:operation name="IssueToken">
      <http:operation location="IssueToken"/>
      <wsdl:input>
        <mime:content part="parameters" type="text/xml"/>
      </wsdl:input>
      <wsdl:output>
        <mime:content part="parameters" type="text/xml"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="sts-ic-symmSoap12Binding" type="tns:sts-ic-symmPortType">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="IssueToken">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input>
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="sts-ic-symm">
    <wsdl:port name="sts-ic-symmHttpsSoap12Endpoint" binding="tns:sts-ic-symmSoap12Binding">
      <soap12:address location="https://identity.cloud-test.wso2.com:9444/services/sts-ic-symm.sts-ic-symmHttpsSoap12Endpoint/"/>
    </wsdl:port>
    <wsdl:port name="sts-ic-symmHttpsEndpoint" binding="tns:sts-ic-symmHttpBinding">
      <http:address location="https://identity.cloud-test.wso2.com:9444/services/sts-ic-symm.sts-ic-symmHttpsEndpoint/"/>
    </wsdl:port>
    <wsdl:port name="sts-ic-symmHttpSoap12Endpoint" binding="tns:sts-ic-symmSoap12Binding">
      <soap12:address location="http://identity.cloud-test.wso2.com:9764/services/sts-ic-symm.sts-ic-symmHttpSoap12Endpoint/"/>
    </wsdl:port>
    <wsdl:port name="sts-ic-symmHttpEndpoint" binding="tns:sts-ic-symmHttpBinding">
      <http:address location="http://identity.cloud-test.wso2.com:9764/services/sts-ic-symm.sts-ic-symmHttpEndpoint/"/>
    </wsdl:port>
    <wsdl:port name="sts-ic-symmHttpsSoap11Endpoint" binding="tns:sts-ic-symmSoap11Binding">
      <soap:address location="https://identity.cloud-test.wso2.com:9444/services/sts-ic-symm.sts-ic-symmHttpsSoap11Endpoint/"/>
    </wsdl:port>
    <wsdl:port name="sts-ic-symmHttpSoap11Endpoint" binding="tns:sts-ic-symmSoap11Binding">
      <soap:address location="http://identity.cloud-test.wso2.com:9764/services/sts-ic-symm.sts-ic-symmHttpSoap11Endpoint/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
